# Generated by Django 5.1.7 on 2025-04-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSevenResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('roll', models.IntegerField()),
                ('StudentID', models.IntegerField()),
                ('bangla', models.FloatField()),
                ('english', models.FloatField()),
                ('math', models.FloatField()),
                ('biology', models.FloatField()),
                ('chemistry', models.FloatField()),
                ('physics', models.FloatField()),
                ('total', models.FloatField()),
                ('avarage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassSevenStudentID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('FatherName', models.CharField(max_length=20)),
                ('MotherNmae', models.CharField(max_length=20)),
                ('StudentID', models.IntegerField()),
                ('roll', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSevenTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('NID', models.IntegerField()),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
