# Generated by Django 5.1.7 on 2025-04-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSIXResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('roll', models.IntegerField(max_length=5)),
                ('student_id', models.IntegerField(max_length=10)),
                ('FatherName', models.CharField(max_length=20)),
                ('bangla', models.FloatField(max_length=5)),
                ('english', models.FloatField(max_length=5)),
                ('math', models.FloatField(max_length=5)),
                ('biology', models.FloatField(max_length=5)),
                ('chemistry', models.FloatField(max_length=5)),
                ('physics', models.FloatField(max_length=5)),
                ('total', models.FloatField(max_length=10)),
                ('avarage', models.FloatField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSixTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=15)),
                ('NID', models.IntegerField(max_length=17)),
                ('password', models.IntegerField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='SixStudentIDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('FatherName', models.CharField(max_length=20)),
                ('MotherName', models.CharField(max_length=20)),
                ('roll', models.IntegerField(max_length=5)),
                ('StudentID', models.IntegerField(max_length=10)),
            ],
        ),
    ]
