# Generated by Django 5.1.7 on 2025-04-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassSix', '0002_sixstudentid_delete_sixstudentids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsixteachers',
            name='password',
            field=models.CharField(max_length=18),
        ),
    ]
